#!/usr/bin/env python3
"""Generated by android-build-broker v1. Regenerate with: broker.py init-repo REPOSITORY"""

from __future__ import annotations

import argparse
import json
import os
import stat
import subprocess
import sys
import time
import uuid
from pathlib import Path

if sys.version_info < (3, 10):
    raise SystemExit("request-android-build requires Python 3.10 or newer")

# This block is deliberately duplicated from source_identity.py: the installed
# client is standalone and must compute exactly the identity checked by worker.py.
exec(compile('''SOURCE_IDENTITY_PLACEHOLDER''', "<source_identity>", "exec"))

PROTOCOL_VERSION = 1


def fail(message: str) -> None:
    print(f"request-android-build: {message}", file=sys.stderr)
    raise SystemExit(1)


def atomic_json(path: Path, value: object, exclusive: bool = False) -> None:
    payload = (json.dumps(value, sort_keys=True, separators=(",", ":")) + "\n").encode()
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    fd = os.open(temporary, flags, 0o600)
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "wb") as output:
            output.write(payload)
            output.flush()
            os.fsync(output.fileno())
        if exclusive:
            try:
                os.link(temporary, path, follow_symlinks=False)
            except FileExistsError:
                fail(f"file already exists: {path}")
            temporary.unlink()
        else:
            os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def repository_root() -> Path:
    result = subprocess.run(["git", "rev-parse", "--show-toplevel"], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if result.returncode:
        fail("run this command inside a Git repository")
    return Path(result.stdout.strip()).resolve()


def broker_heartbeat(repository: Path) -> dict[str, object]:
    root = repository / ".artifacts" / "android"
    heartbeat_path = root / "heartbeat.json"
    try:
        heartbeat = json.loads(heartbeat_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"no running broker heartbeat: {exc}")
    now = int(time.time())
    expected = {"protocolVersion", "brokerSessionId", "targetRepository", "pid", "updatedAt"}
    if type(heartbeat) is not dict or set(heartbeat) != expected:
        fail("invalid broker heartbeat")
    session = heartbeat.get("brokerSessionId")
    if type(session) is not str or type(heartbeat.get("updatedAt")) is not int or now - heartbeat["updatedAt"] > 5 or heartbeat["updatedAt"] > now + 30:
        fail("broker heartbeat is stale")
    if heartbeat.get("targetRepository") != str(repository):
        fail("broker heartbeat targets a different repository")
    return heartbeat


def main() -> None:
    parser = argparse.ArgumentParser(description="Request an Android build from the local broker")
    parser.add_argument("--broker-status", action="store_true", help="report whether this repository's broker is running without requesting a build")
    args = parser.parse_args()
    repository = repository_root()
    heartbeat = broker_heartbeat(repository)
    if args.broker_status:
        print(json.dumps({
            "running": True,
            "brokerSessionId": heartbeat["brokerSessionId"],
            "pid": heartbeat["pid"],
            "updatedAt": heartbeat["updatedAt"],
        }, separators=(",", ":")))
        return
    root = repository / ".artifacts" / "android"
    now = int(time.time())
    session = heartbeat["brokerSessionId"]
    identity = compute_source_identity(repository)
    request_id = str(uuid.uuid4())
    requests = root / "requests"
    result_dir = root / "results" / request_id
    for directory in (root, requests, root / "claimed", root / "results", result_dir):
        directory.mkdir(mode=0o700, parents=True, exist_ok=True)
        info = directory.lstat()
        if not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode) or info.st_uid != os.geteuid() or info.st_mode & 0o022:
            fail(f"unsafe runtime directory: {directory}")
    status_path = result_dir / "status.json"
    atomic_json(status_path, {"protocolVersion": 1, "requestId": request_id, "state": "queued", "updatedAt": now}, exclusive=True)
    request = {
        "protocolVersion": PROTOCOL_VERSION,
        "requestId": request_id,
        "createdAt": now,
        "brokerSessionId": session,
        "head": identity.head,
        "worktreeDigest": identity.digest,
    }
    atomic_json(requests / f"{request_id}.json", request, exclusive=True)
    print(json.dumps({"requestId": request_id, "statusPath": str(status_path.relative_to(repository))}, separators=(",", ":")))


if __name__ == "__main__":
    main()
