from __future__ import annotations

import argparse
import json
import subprocess
import tempfile
import time
import unittest
from pathlib import Path
from unittest import mock

import broker
from tests.support import repository


class InitTests(unittest.TestCase):
    def test_init_installs_client_and_respects_equivalent_ignore(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            repo = repository(Path(temporary) / "repo")
            args = argparse.Namespace(repository=str(repo))
            with mock.patch("builtins.input", return_value="y"):
                self.assertEqual(0, broker.init_repo(args))
            client = repo / "scripts" / "request-android-build.py"
            self.assertTrue(client.is_file())
            self.assertTrue(client.stat().st_mode & 0o111)
            self.assertEqual(1, (repo / ".gitignore").read_text().count(".artifacts/"))

    def test_generated_client_reports_broker_status_without_requesting_build(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            repo = repository(Path(temporary) / "repo")
            with mock.patch("builtins.input", return_value="y"):
                broker.init_repo(argparse.Namespace(repository=str(repo)))
            runtime = repo / ".artifacts" / "android"
            runtime.mkdir(parents=True)
            session = "123e4567-e89b-42d3-a456-426614174000"
            (runtime / "heartbeat.json").write_text(json.dumps({
                "protocolVersion": 1, "brokerSessionId": session, "targetRepository": str(repo),
                "pid": 1234, "updatedAt": int(time.time()),
            }))
            result = subprocess.run(
                [repo / "scripts" / "request-android-build.py", "--broker-status"],
                cwd=repo, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            )
            self.assertEqual(0, result.returncode, result.stderr)
            self.assertEqual({"running": True, "brokerSessionId": session, "pid": 1234, "updatedAt": json.loads(result.stdout)["updatedAt"]}, json.loads(result.stdout))
            self.assertFalse((runtime / "requests").exists())

    def test_init_refuses_unknown_client_and_decline_changes_nothing(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            repo = repository(Path(temporary) / "repo")
            scripts = repo / "scripts"; scripts.mkdir()
            client = scripts / "request-android-build.py"
            client.write_text("unknown\n")
            with self.assertRaises(ValueError):
                broker.init_repo(argparse.Namespace(repository=str(repo)))
            client.unlink()
            with mock.patch("builtins.input", return_value="n"):
                self.assertEqual(1, broker.init_repo(argparse.Namespace(repository=str(repo))))
            self.assertFalse(client.exists())

    def test_init_updates_previous_generated_client(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            repo = repository(Path(temporary) / "repo")
            scripts = repo / "scripts"; scripts.mkdir()
            client = scripts / "request-android-build.py"
            client.write_text("#!/usr/bin/env python3\n\"\"\"Generated by android-build-broker v1. Regenerate with: broker.py init-repo REPOSITORY\"\"\"\nold\n")
            with mock.patch("builtins.input", return_value="y"):
                self.assertEqual(0, broker.init_repo(argparse.Namespace(repository=str(repo))))
            self.assertIn("--broker-status", client.read_text())

    def test_init_refuses_symlinked_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            repo = repository(root / "repo")
            outside = root / "outside"; outside.mkdir()
            (repo / "scripts").symlink_to(outside, target_is_directory=True)
            with self.assertRaises(ValueError):
                broker.init_repo(argparse.Namespace(repository=str(repo)))
            (repo / "scripts").unlink()
            (repo / ".gitignore").unlink()
            (repo / ".gitignore").symlink_to(outside / "ignore")
            with self.assertRaises(ValueError):
                broker.init_repo(argparse.Namespace(repository=str(repo)))


if __name__ == "__main__":
    unittest.main()
